name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # ğŸ‘ˆ this makes the action manually triggerable

jobs:
  playwright-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ“¥ Checkout Code
      uses: actions/checkout@v4
    
    - name: ğŸ› ï¸ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
      
    - name: ğŸ”§ Install dependencies
      run: npm ci

    - name: ğŸŒ Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: ğŸ§ª Run Playwright tests
      run: npx playwright test --project=chromium -g "test-1.spec.ts"
      
    # - name: ğŸ“¦ Archive Test Results
    #   if: success() || failure()    
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: playwright-report
    #     path: test-reports/playwright-report/
    #     retention-days: 1
        
    - name: ğŸ–¥ï¸ Install CTRF CLI
      run: npm install -g github-actions-ctrf

    - name: ğŸ“‘ Publish Test Summary Results
      run: npx github-actions-ctrf ctrf/ctrf-report.json

    - name: ğŸ­ Add Playwright Summary to Job
      run: node test-summary.ts

